train: ../combined_dataset/images/train
val: ../combined_dataset/images/val
test: ../combined_dataset/images/test

nc: 17
names: [
    'person', 
    'car',
    'Green Light', 
    'Red Light', 
    'Speed Limit 10', 
    'Speed Limit 100',
    'Speed Limit 110',
    'Speed Limit 120',
    'Speed Limit 20', 
    'Speed Limit 30',
    'Speed Limit 40', 
    'Speed Limit 50',
    'Speed Limit 60', 
    'Speed Limit 70',
    'Speed Limit 80',
    'Speed Limit 90',
    'Stop'
]
